In [2]:
import numpy as np

In [3]:
a= [1,2,3,4,5,]

In [4]:
type(a)

list

In [5]:
a1=np.array(a)

In [6]:
type(a1)

numpy.ndarray

In [7]:
# to find dimension
a1.ndim

1

In [8]:
#number of rows and coloums availabel
a1.shape

(5,)

In [9]:
a=np.array([[1,2,3],
          [4,5,6,]])

In [10]:
a.ndim

2

In [11]:
a.shape

(2, 3)

In [12]:
#for all one array
a.dtype

dtype('int32')

In [13]:
 a=np.ones(5)

In [14]:
a

array([1., 1., 1., 1., 1.])

In [15]:
a.dtype

dtype('float64')

In [16]:
a=np.ones((3,4))

In [17]:
#for all zero array
a=np.zeros((1,3))

In [18]:
a

array([[0., 0., 0.]])

In [19]:
a.ndim

2

In [20]:
a=np.zeros((1,2),dtype=bool)

In [21]:
a

array([[False, False]])

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9,11])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [24]:
#it is basically range
a=np.arange(1,11)

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a=np.arange(12,200,5)

In [27]:
a

array([ 12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,  67,  72,
        77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127, 132, 137,
       142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192, 197])

In [28]:
#random 50 number between 1-10
a=np.linspace(1,10)

In [29]:
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [30]:
#specified 15 no. between 1-10
a=np.linspace(1,10,15)

In [31]:
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [32]:
a=np.arange(1,10)

In [33]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a=np.arange(1,16)

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
#to create 2 or 3 dimensions
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
a.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [39]:
a.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [40]:
 a=np.arange(1,25).reshape(4,6)

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [42]:
 a.ndim

2

In [43]:
  b=np.arange(1,25).reshape(2,4,3)

In [44]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [45]:
b.ndim

3

In [46]:
b=b.ravel( )

In [47]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [48]:
b.ndim

1

In [49]:
b=b.flatten(order="F" )

In [50]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [51]:
 a=np.arange(1,16).reshape(3,5)

In [52]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [53]:
a.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [54]:
a=np.arange(1,25)

In [55]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [56]:
 a1=a.reshape(2,4,3)
    

In [57]:
a1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [58]:
a1.ndim

3

In [59]:
a1=a1.reshape(1 ,-1)

In [60]:
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
a1.ndim

2

In [62]:
a1=a1.reshape(-1 ,1)

In [63]:
a1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [64]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,10).reshape(3,3)

In [65]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a1=np.add(a,b)

In [68]:
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [69]:
a2=np.subtract(a,b)

In [70]:
a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
a3=np.divide(a,b)

In [72]:
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
a.min()

1

In [74]:
a.max()

9

In [75]:
a.min(axis=0)

array([1, 2, 3])

In [76]:
a.max(axis=1)

array([3, 6, 9])

In [77]:
 a.min(axis=0)

array([1, 2, 3])

In [78]:
np.argmax(a)

8

In [79]:
np.argmin(a)

0

In [80]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
  np.sum(a,axis=0)

array([12, 15, 18])

In [82]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [83]:
# sum of diagonal
np.trace(a)

15

In [84]:
# mean value
np.mean(a)

5.0

In [85]:
#standard deviation
np.std(a)

2.581988897471611

In [86]:
#variance
np.var(a)

6.666666666666667

In [87]:
# square root
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [88]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [89]:
a=np.arange(1,101).reshape(10,10)

In [90]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [91]:
#shows 3rd row
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [92]:
#only acces row  
a[3:6]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [93]:
#access both rows and coloumns
a[3,3]

34

In [94]:
a[3:6,3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [95]:
a[:,3:8]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

In [96]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [97]:
a[:,3:10:2]

array([[  4,   6,   8,  10],
       [ 14,  16,  18,  20],
       [ 24,  26,  28,  30],
       [ 34,  36,  38,  40],
       [ 44,  46,  48,  50],
       [ 54,  56,  58,  60],
       [ 64,  66,  68,  70],
       [ 74,  76,  78,  80],
       [ 84,  86,  88,  90],
       [ 94,  96,  98, 100]])

In [98]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,10).reshape(3,3)

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [102]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [120]:
a=np.arange(1,17).reshape(4,4)
b=np.arange(17,33).reshape(4,4)

In [121]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [108]:
 np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [110]:
 np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [113]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [115]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [122]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [126]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [129]:
np.split(a,2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [130]:
s=np.array([11,22,33,44,55,66,77])

In [131]:
s

array([11, 22, 33, 44, 55, 66, 77])

In [132]:
np.split(s,[2])

[array([11, 22]), array([33, 44, 55, 66, 77])]

In [133]:
np.split(s,[3])

[array([11, 22, 33]), array([44, 55, 66, 77])]

In [137]:
np.split(s,[2,6])

[array([11, 22]), array([33, 44, 55, 66]), array([77])]

In [138]:
np.random.random()

0.468400658684466

In [139]:
np.random.random(5)

array([0.24757939, 0.86443524, 0.812641  , 0.0074798 , 0.74527094])

In [141]:
s=np.random.random((4,4))

In [142]:
s

array([[0.0389497 , 0.40588333, 0.88941047, 0.51215777],
       [0.8399723 , 0.40287761, 0.62977151, 0.45670033],
       [0.15051591, 0.24095281, 0.14845125, 0.31936388],
       [0.48806183, 0.62096093, 0.30127717, 0.49849201]])

In [146]:
s.ndim

2

In [147]:
s=np.random.random((3,3,3))

In [148]:
s

array([[[0.67693513, 0.83032482, 0.82630796],
        [0.98683712, 0.15006471, 0.02118475],
        [0.73017268, 0.22583963, 0.04298158]],

       [[0.05497962, 0.00594326, 0.34426214],
        [0.34827301, 0.21887571, 0.03412247],
        [0.2997312 , 0.87596242, 0.20739765]],

       [[0.28864929, 0.91480614, 0.09324175],
        [0.87170033, 0.14216287, 0.78752782],
        [0.30884563, 0.53361909, 0.13212403]]])

In [149]:
a=np.linspace(1,15,25)

In [150]:
a

array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
        3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
        6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
        9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
       12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ])

In [151]:
np.random.choice(a)

4.5

In [153]:
 np.random.choice(a,(3,3))

array([[13.83333333,  1.        , 15.        ],
       [ 5.66666667,  9.75      ,  9.16666667],
       [13.25      ,  8.        ,  9.75      ]])

In [154]:
np.random.permutation(a)

array([13.83333333,  8.58333333,  9.75      , 13.25      , 10.33333333,
       14.41666667, 12.66666667, 10.91666667,  3.91666667,  8.        ,
        6.83333333,  2.16666667,  5.08333333, 12.08333333,  1.58333333,
        2.75      ,  6.25      , 15.        ,  3.33333333,  9.16666667,
        5.66666667,  7.41666667, 11.5       ,  1.        ,  4.5       ])

In [156]:
a=np.random.uniform(1,100,25)

In [157]:
a

array([32.07815358, 65.2337656 , 20.67349085, 87.38351315,  1.42662651,
       19.88613095,  9.86041736, 75.85493258, 82.92999481, 74.72611963,
       49.42327955, 49.18145229, 32.6469481 , 41.49527307, 92.9332157 ,
       71.53672258, 59.61492498, 99.69939016,  3.48092192, 23.34141493,
       99.38282253, 33.99658556, 53.52550403, 75.62601638, 80.02208638])

In [160]:
b=np.random.normal(20,5,100)

In [161]:
b

array([21.4986972 , 19.48612705, 25.02957747, 10.33482502, 20.44268164,
       18.91034478, 19.42380921, 14.72558095, 11.0844971 , 26.01917992,
       26.46085289, 17.17433605, 27.45226324, 25.46103572, 19.46600318,
       20.72161787, 12.80789471,  9.84928806, 21.34929913, 21.0712508 ,
       15.6501363 , 23.8988045 ,  8.82046507, 11.66984221, 27.36346551,
       24.795446  ,  8.42152172, 13.82190449, 21.91563092, 19.70585014,
       20.02789504, 19.45140786, 23.90920931, 26.68920859, 13.70188682,
       18.7889846 , 20.24622721, 23.14206578, 21.88161279, 12.61132053,
       18.23393434, 10.53630259, 18.00912177, 20.0927276 , 15.92188149,
       23.18685988, 16.26504686, 24.80410367, 19.54000796, 29.15414165,
       12.3940058 , 24.90675364, 18.1985667 , 16.31464547, 12.83081851,
       17.28194639, 17.71534112, 21.91530421, 21.91602278, 16.51841224,
       20.65149725, 11.4598928 , 14.53831985, 19.4380942 , 25.31330897,
       16.68737345, 21.01368262, 23.95971623, 23.57904635, 27.38

In [171]:
s="python"
s1=" Data science"

In [172]:
np.char.add(s, s1)

array('python Data science', dtype='<U19')

In [173]:
np.char.split(s1)

array(list(['Data', 'science']), dtype=object)

In [174]:
 np.char.center(s,15,'*')

array('*****python****', dtype='<U15')